# Generated by Django 4.0.3 on 2024-02-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_cartitem_added_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='The status of the shopping cart.', max_length=10),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(help_text='The user this shopping cart belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
